config/routes.rb
Rails.application.routes.draw do



  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users, :controllers => {registrations: 'registrations'}, :only =>[:show]


  resources :products
  resource :product_items

  resources :carts



  root to: 'products#index'


end

app/models/product_item.rb
class ProductItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart



  def total_price
    product.price * product_count
  end



end

app/controllers/product_items_controller.rb
class ProductItemsController < InheritedResources::Base
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_product_item, only: [:show, :edit, :update, :destroy]


  def create

    product = Product.find(params[:product_id])
    @product_item = @cart.add_product(product.id)
    respond_to do |format|
      if @product_item.save
        format.html { redirect_to products_url, notice: 'Line item was successfully created.' }
        format.js  {@current_item = @product_item}
        format.json { render action: 'show',
                             status: :created, location: @product_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @product_item.errors,
                             status: :unprocessable_entity }
      end

    end
  end

def update

end


def destroy

end

    private

# Never trust parameters from the scary internet, only allow the white
# list through.
    def product_item_params
      params.require(:product_item).permit(:product_id, :cart_id)
    end

  def set_product_item
    @product_item = Product.find(params[:id])
  end





end

app/helpers/product_items_helper.rb
module ProductItemsHelper

  def current_item?




  end


end

app/views/product_items/_form.html.slim
= simple_form_for(@product_item) do |f|
  = f.error_notification

  .form-inputs
    = f.association :product
    = f.association :cart

  .form-actions
    = f.button :submit

app/views/product_items/_product_item.slim
- if product_item == @current_item
  tr#current_item
    td.product-image = image_tag(product_item.product.image.url(:thumb))
    td.product-title = product_item.product.title
    td.product-count = product_item.product_count
    td.total-price   = number_to_currency(product_item.total_price)
- else
  tr
    td.product-image = image_tag(product_item.product.image.url(:thumb))
    td.product-title = product_item.product.title
    td.product-count = product_item.product_count
    td.total-price = number_to_currency(product_item.total_price)

app/views/product_items/create.js.erb
if ($('#cart tr')) { $('#cart').slideDown(200).show('fade', 200) }
    $('#cart').html("<%= escape_javascript render(@cart) %>");

$('#current_item').css({'background-color':'yellow'}).
animate({'background-color':'#EEE'}, 500).fadeIn(1000)

app/views/product_items/edit.html.slim
h1 Editing product_item

== render 'form'

= link_to 'Show', @product_item
'|
= link_to 'Back', product_items_path

app/views/product_items/index.html.slim
h1 Listing product_items

table
  thead
    tr
      th Product
      th Cart
      th
      th
      th

  tbody
    - @product_items.each do |product_item|
      tr
        td = product_item.product
        td = product_item.cart
        td = link_to 'Show', product_item
        td = link_to 'Edit', edit_product_item_path(product_item)
        td = link_to 'Destroy', product_item, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Product item', new_product_item_path

app/views/product_items/new.html.slim
h1 New product_item

== render 'form'

= link_to 'Back', product_items_path

app/views/product_items/show.html.slim
p
  strong Product:
  = @product_item.product
p
  strong Cart:
  = @product_item.cart

= link_to 'Edit', edit_product_item_path(@product_item)
'|
= link_to 'Back', product_items_path