config/routes.rb
Rails.application.routes.draw do



  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users, :controllers => {registrations: 'registrations'}, :only =>[:show]


  resources :products
  resource :product_items

  resources :carts



  root to: 'products#index'


end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :product_items, dependent: :destroy


  def add_product(product_id)

    product = Product.find(product_id)
    current_item = product_items.where(:product_id => product.id).first
    if current_item
      current_item.update_attributes :product_count => current_item.product_count + 1
    else
      current_item = product_items.build(:product_id => product_id)
      product_items << current_item
    end
    current_item
  end

  def total_price

    product_items.to_a.sum { |item| item.total_price}

  end



end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart



  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
     session[:cart_id] = nil
    respond_to do |format|
       format.html { redirect_to root_path}
       format.js {render :layout => false}
      format.json { head :no_content }
    end
  end


  private
    def cart_params
      params.require(:cart).permit()
    end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: 'Invalid cart'
  end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.slim
h2 Ваша корзина

table
  thead
    tr
      th
      th Title
      th Count
      th Price

  = render cart.product_items.sort_by(&:id)
  td
  td
  td Total:
  td = number_to_currency(cart.total_price)

.pull-right = button_to 'Empty cart',  cart, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-info empty-cart', remote: true
  /
  /
  /= link_to 'Edit', edit_cart_path(cart)
  /'|
  /= link_to 'Back', root_path

app/views/carts/_form.html.slim
= simple_form_for(@cart) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/carts/destroy.js.erb
//#destroy

$('#cart').fadeOut(200).slideUp(400);

app/views/carts/edit.html.slim
h1 Editing cart

== render 'carts/show'

= link_to 'Show', @cart
'|
= link_to 'Back', carts_path

app/views/carts/index.html.slim
h1 Listing carts

table
  thead
    tr
      th
      th
      th

  tbody
    - @carts.each do |cart|
      tr
        td = link_to 'Show', cart
        td = link_to 'Edit', edit_cart_path(cart)
        td = link_to 'Destroy', cart, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.slim
h1 New cart

== render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.slim
= render @cart