config/routes.rb
Rails.application.routes.draw do



  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users, :controllers => {registrations: 'registrations'}, :only =>[:show]


  resources :products
  resource :product_items

  resources :carts



  root to: 'products#index'


end

app/models/product.rb
class Product < ActiveRecord::Base
 belongs_to :category

 has_many :product_items

 before_destroy :ensure_not_refernced_by_any_product_item
 attr_accessor :delete_image

 after_destroy { image.clear if delete_image == '0' }

  validates :title, :description,  :price, presence: true
  validates :title , uniqueness: true

  validates :price, numericality: {greater_than_or_equal_to: 0.01}

  has_attached_file :image,
                    :path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
                    :url => "/system/:attachment/:id/:basename_:style.:extension",
                    :styles => {
                        :thumb    => ['100x100#',  :jpg, :quality => 70],
                        :preview  => ['320x240#',  :jpg, :quality => 70],
                        :large    => ['600>',      :jpg, :quality => 70],
                        :rectangle => ['1200x400#',  :jpg, :quality => 70],
                        :retina   => ['1200>',     :jpg, :quality => 30]
                    },
                    :convert_options => {
                        :thumb    => '-set colorspace sRGB -strip',
                        :preview  => '-set colorspace sRGB -strip',
                        :large    => '-set colorspace sRGB -strip',
                        :rectangle    => '-set colorspace sRGB -strip',
                        :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
                    }

  validates_attachment :image,
                       :presence => true,
                       :size => { :in => 0..50.megabytes },
                       :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/,  message: 'URL должен указывать на изображение формата GIF, JPG или PNG.'}



def self.latest
  Product.order(:updated_at).last

end

 private

 def ensure_not_referenced_by_any_product_item
    if products.empty?
      return true
    else
      errors.add(:base, 'существуют товарные позиции')
      return false
    end
 end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper
  include CurrentCart

  before_action :set_cart

  before_action :count_index_visits, only: [:index]

  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_product, only: [:show]

  respond_to :html, :xml, :json


  def index
    @products = Product.all
    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    flash[:notice] = 'Product was successfully created.' if @product.save

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'User was successfully created.' }
        format.js   {}
        format.json { render json: @product,
                      status: :created,
                      location: @product
                    }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    flash[:notice] = 'Product was successfully updated.' if @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  def chart
    render json: Product.group_by_day(:completed_at).count
  end




  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :image, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

  def reset_index_visits
    session[:counter]=0
  end

  def count_index_visits
    if session[:counter].nil?
      reset_index_visits
    else
      session[:counter]+=1
    end
  end

  def report_index_visits
    if session[:counter]==0 then
      response ="Welcome!"
    else
      counter = pluralize(session[:counter], 'time')
      response= "You are #{counter} on this page "
    end
    return response

  end



end

app/views/products/_form.html.slim
= bootstrap_form_for(@product, layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-6" ) do |f|
  = f.error_summary


  = f.text_field :title , class: "title"
  = f.text_area :description
  = f.file_field :image
  = f.text_field :price

  .form-actions
    = f.button :submit

app/views/products/index.html.slim
h1.title Products
= report_index_visits

/= link_to 'Edit Cart', cart_url(@cart)

.row

  - @products.each do |product|

      .col-sm-6.col-md-4
        .thumbnail
          .image-container
            = link_to image_tag(product.image.url(:preview), class: 'img-rounded img-responsive'), product
            .product-buy
               = button_to 'Add to Cart', product_items_path(product_id: product), remote: true

            h4.product-price
              = number_to_currency(product.price)
          .caption
             h3 = link_to product.title, product
             p = product.description

app/views/products/show.html.slim
/p#notice = notice

/== render (@product.line_items)
h1.product-title_show
  = @product.title
ol.breadcrumb
   li = link_to 'Home', root_path
   li = link_to @product.id, root_path
   li.active = @product.title
= image_tag(@product.image.url(:rectangle), class: 'img-responsive')

h3
  = @product.description

h4
  = number_to_currency(@product.price)